name: Deploy to Flywheel

on:
  push:
    branches:
      - main    # Production env
      - staging # Staging environment

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
      url: ${{ github.ref == 'refs/heads/main' && 'https://stompinggroundcomedy.org' || 'https://sg.flywheelstaging.com' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer

      - name: Install Composer dependencies
        run: |
          echo "Installing Composer dependencies..."
          composer install --no-dev --optimize-autoloader --verbose || {
            echo "::error::Composer install failed. Check composer.json and composer.lock for errors."
            echo "::group::Composer Debug Info"
            composer diagnose
            composer show
            echo "::endgroup::"
            exit 1
          }
          echo "Composer dependencies installed successfully."

      # Commenting out Node.js and build steps until frontend build process is set up
      # - name: Setup Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '18'
      #     cache: 'npm'

      # - name: Install NPM dependencies
      #   run: |
      #     echo "Installing NPM dependencies..."
      #     npm ci --verbose || {
      #       echo "::error::NPM install failed. Check package.json and package-lock.json for errors."
      #       echo "::group::NPM Debug Info"
      #       npm list
      #       npm config list
      #       echo "::endgroup::"
      #       exit 1
      #     }
      #     echo "NPM dependencies installed successfully."

      # - name: Build assets
      #   run: |
      #     echo "Building assets..."
      #     npm run build --verbose || {
      #       echo "::error::Asset build failed. Check webpack configuration and build scripts."
      #       echo "::group::Build Debug Info"
      #       npm run build --verbose
      #       echo "::endgroup::"
      #       exit 1
      #     }
      #     echo "Assets built successfully."

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add Flywheel to known hosts
        run: |
          echo "Setting up SSH known hosts..."
          mkdir -p ~/.ssh
          ssh-keyscan -H ssh.getflywheel.com >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
          echo "SSH known hosts configured."

      - name: Test SSH Connection
        run: |
          echo "Testing SSH connection to Flywheel..."
          SSH_USER=${{ github.ref == 'refs/heads/main' && 'stompingground+stomping-ground' || 'stompingground+staging+stomping-ground' }}
          echo "Using SSH user: $SSH_USER"
          
          if ! ssh -v -o BatchMode=yes -o ConnectTimeout=5 $SSH_USER@ssh.getflywheel.com echo "SSH connection successful"; then
            echo "::error::SSH connection failed. Check SSH key and permissions."
            echo "::group::SSH Debug Info"
            ssh -v $SSH_USER@ssh.getflywheel.com
            echo "::endgroup::"
            exit 1
          fi
          echo "SSH connection successful."

      - name: Check Deployment Paths
        run: |
          SSH_USER=${{ github.ref == 'refs/heads/main' && 'stompingground+stomping-ground' || 'stompingground+staging+stomping-ground' }}
          THEMES_PATH="/www/wp-content/themes"
          # PLUGINS_PATH="/www/wp-content/plugins"
          echo "Checking deployment paths..."
          echo "Themes path: $THEMES_PATH"
          # echo "Plugins path: $PLUGINS_PATH"
          
          if ! ssh -v $SSH_USER@ssh.getflywheel.com "[ -d $THEMES_PATH ]"; then
            echo "::error::Themes directory does not exist: $THEMES_PATH"
            echo "::group::Path Debug Info"
            ssh -v $SSH_USER@ssh.getflywheel.com "ls -la /www/wp-content"
            echo "::endgroup::"
            exit 1
          fi
          
          # if ! ssh -v $SSH_USER@ssh.getflywheel.com "[ -d $PLUGINS_PATH ]"; then
          #   echo "::error::Plugins directory does not exist: $PLUGINS_PATH"
          #   echo "::group::Path Debug Info"
          #   ssh -v $SSH_USER@ssh.getflywheel.com "ls -la /www/wp-content"
          #   echo "::endgroup::"
          #   exit 1
          # fi
          echo "Themes deployment path exists and is accessible."

      - name: Create Backup
        run: |
          SSH_USER=${{ github.ref == 'refs/heads/main' && 'stompingground+stomping-ground' || 'stompingground+staging+stomping-ground' }}
          TIMESTAMP=$(date +%Y%m%d_%H%M%S)
          THEMES_PATH="/www/wp-content/themes"
          BACKUP_PATH="/tmp/theme_backup_${TIMESTAMP}"
          
          echo "Creating backup at $BACKUP_PATH"
          if ! ssh -v $SSH_USER@ssh.getflywheel.com "mkdir -p $BACKUP_PATH && cp -r $THEMES_PATH $BACKUP_PATH/"; then
            echo "::warning::Backup creation failed - continuing with deployment"
            echo "::group::Backup Debug Info"
            ssh -v $SSH_USER@ssh.getflywheel.com "ls -la /tmp/ | grep theme_backup"
            echo "::endgroup::"
          else
            echo "Backup created successfully at $BACKUP_PATH"
            echo "Note: This is a temporary backup in /tmp/ that will be cleaned up automatically"
          fi

      - name: Deploy Themes
        run: |
          SSH_USER=${{ github.ref == 'refs/heads/main' && 'stompingground+stomping-ground' || 'stompingground+staging+stomping-ground' }}
          THEMES_PATH="/www/wp-content/themes"
          echo "Deploying themes to $THEMES_PATH"
          
          # Deploy themes with dry-run first
          echo "Performing dry run for themes..."
          if ! rsync -avzn --delete --stats ./themes/ $SSH_USER@ssh.getflywheel.com:$THEMES_PATH; then
            echo "::error::Themes dry run failed"
            echo "::group::Themes Dry Run Debug Info"
            rsync -avzn --delete --stats --verbose ./themes/ $SSH_USER@ssh.getflywheel.com:$THEMES_PATH
            echo "::endgroup::"
            exit 1
          fi
          echo "Themes dry run successful."
          
          # Actual themes deployment
          echo "Starting actual themes deployment..."
          if ! rsync -avz --delete --stats ./themes/ $SSH_USER@ssh.getflywheel.com:$THEMES_PATH; then
            echo "::error::Themes deployment failed"
            echo "::group::Themes Deployment Debug Info"
            rsync -avz --delete --stats --verbose ./themes/ $SSH_USER@ssh.getflywheel.com:$THEMES_PATH
            echo "::endgroup::"
            exit 1
          fi
          echo "Themes deployment completed successfully."

      # Commenting out plugin deployment for now
      # - name: Deploy Plugins
      #   run: |
      #     SSH_USER=${{ github.ref == 'refs/heads/main' && 'stompingground+stomping-ground' || 'stompingground+staging+stomping-ground' }}
      #     PLUGINS_PATH="/www/wp-content/plugins"
      #     echo "Deploying plugins to $PLUGINS_PATH"
      #     
      #     # Deploy plugins with dry-run first
      #     echo "Performing dry run for plugins..."
      #     if ! rsync -avzn --delete --stats ./plugins/ $SSH_USER@ssh.getflywheel.com:$PLUGINS_PATH; then
      #       echo "::error::Plugins dry run failed"
      #       echo "::group::Plugins Dry Run Debug Info"
      #       rsync -avzn --delete --stats --verbose ./plugins/ $SSH_USER@ssh.getflywheel.com:$PLUGINS_PATH
      #       echo "::endgroup::"
      #       exit 1
      #     fi
      #     echo "Plugins dry run successful."
      #     
      #     # Actual plugins deployment
      #     echo "Starting actual plugins deployment..."
      #     if ! rsync -avz --delete --stats ./plugins/ $SSH_USER@ssh.getflywheel.com:$PLUGINS_PATH; then
      #       echo "::error::Plugins deployment failed"
      #       echo "::group::Plugins Deployment Debug Info"
      #       rsync -avz --delete --stats --verbose ./plugins/ $SSH_USER@ssh.getflywheel.com:$PLUGINS_PATH
      #       echo "::endgroup::"
      #       exit 1
      #     fi
      #     echo "Plugins deployment completed successfully."

      - name: Verify Deployment
        run: |
          SSH_USER=${{ github.ref == 'refs/heads/main' && 'stompingground+stomping-ground' || 'stompingground+staging+stomping-ground' }}
          THEMES_PATH="/www/wp-content/themes"
          # PLUGINS_PATH="/www/wp-content/plugins"
          echo "Verifying deployment..."
          
          # Check if critical theme files exist
          echo "Checking theme files..."
          if ! ssh -v $SSH_USER@ssh.getflywheel.com "[ -d $THEMES_PATH/sg25 ]"; then
            echo "::error::sg25 theme directory not found"
            echo "::group::Theme Check Debug Info"
            ssh -v $SSH_USER@ssh.getflywheel.com "ls -la $THEMES_PATH"
            echo "::endgroup::"
            exit 1
          fi
          
          if ! ssh -v $SSH_USER@ssh.getflywheel.com "[ -f $THEMES_PATH/sg25/style.css ]"; then
            echo "::error::sg25 theme style.css not found"
            echo "::group::Theme File Check Debug Info"
            ssh -v $SSH_USER@ssh.getflywheel.com "ls -la $THEMES_PATH/sg25"
            echo "::endgroup::"
            exit 1
          fi
          
          # Commenting out plugin verification for now
          # # Check if critical plugin files exist
          # echo "Checking plugin files..."
          # if ! ssh -v $SSH_USER@ssh.getflywheel.com "[ -d $PLUGINS_PATH/utd-shared-core ]"; then
          #   echo "::error::utd-shared-core plugin directory not found"
          #   echo "::group::Plugin Check Debug Info"
          #   ssh -v $SSH_USER@ssh.getflywheel.com "ls -la $PLUGINS_PATH"
          #   echo "::endgroup::"
          #   exit 1
          # fi
          # 
          # if ! ssh -v $SSH_USER@ssh.getflywheel.com "[ -f $PLUGINS_PATH/utd-shared-core/utd-shared-core.php ]"; then
          #   echo "::error::utd-shared-core plugin main file not found"
          #   echo "::group::Plugin File Check Debug Info"
          #   ssh -v $SSH_USER@ssh.getflywheel.com "ls -la $PLUGINS_PATH/utd-shared-core"
          #   echo "::endgroup::"
          #   exit 1
          # fi
          
          echo "All critical theme files verified successfully." 