name: Deploy to Flywheel

on:
  push:
    branches:
      - main    # Production
      - staging # Staging environment

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
      url: ${{ github.ref == 'refs/heads/main' && 'https://stomping-ground.com' || 'https://staging.stomping-ground.com' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer

      - name: Install Composer dependencies
        run: |
          composer install --no-dev --optimize-autoloader || {
            echo "Composer install failed"
            exit 1
          }

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install NPM dependencies
        run: |
          npm ci || {
            echo "NPM install failed"
            exit 1
          }

      - name: Build assets
        run: |
          npm run build || {
            echo "Asset build failed"
            exit 1
          }

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add Flywheel to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ssh.getflywheel.com >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Test SSH Connection
        run: |
          echo "Testing SSH connection to Flywheel..."
          SSH_USER=${{ github.ref == 'refs/heads/main' && 'stompingground+stomping-ground' || 'stompingground+staging+stomping-ground' }}
          ssh -v -o BatchMode=yes -o ConnectTimeout=5 $SSH_USER@ssh.getflywheel.com echo "SSH connection successful" || {
            echo "SSH connection failed"
            exit 1
          }

      - name: Check Deployment Path
        run: |
          SSH_USER=${{ github.ref == 'refs/heads/main' && 'stompingground+stomping-ground' || 'stompingground+staging+stomping-ground' }}
          DEPLOY_PATH=${{ github.ref == 'refs/heads/main' && '/stompingground/stomping-ground' || '/stompingground/stomping-ground_staging' }}
          echo "Checking deployment path: $DEPLOY_PATH"
          ssh -v $SSH_USER@ssh.getflywheel.com "[ -d $DEPLOY_PATH ]" || {
            echo "Deployment path does not exist: $DEPLOY_PATH"
            exit 1
          }

      - name: Create Backup
        run: |
          SSH_USER=${{ github.ref == 'refs/heads/main' && 'stompingground+stomping-ground' || 'stompingground+staging+stomping-ground' }}
          TIMESTAMP=$(date +%Y%m%d_%H%M%S)
          DEPLOY_PATH=${{ github.ref == 'refs/heads/main' && '/stompingground/stomping-ground' || '/stompingground/stomping-ground_staging' }}
          BACKUP_PATH="/backups/backup_${TIMESTAMP}"
          
          echo "Creating backup at $BACKUP_PATH"
          ssh -v $SSH_USER@ssh.getflywheel.com "mkdir -p $BACKUP_PATH && cp -r $DEPLOY_PATH/* $BACKUP_PATH/" || {
            echo "Backup creation failed"
            exit 1
          }

      - name: Deploy to Flywheel
        run: |
          SSH_USER=${{ github.ref == 'refs/heads/main' && 'stompingground+stomping-ground' || 'stompingground+staging+stomping-ground' }}
          DEPLOY_PATH=${{ github.ref == 'refs/heads/main' && '/stompingground/stomping-ground' || '/stompingground/stomping-ground_staging' }}
          echo "Deploying to $DEPLOY_PATH"
          
          # Deploy with dry-run first
          rsync -avzn --delete ./ $SSH_USER@ssh.getflywheel.com:$DEPLOY_PATH || {
            echo "Dry run failed"
            exit 1
          }
          
          # Actual deployment
          rsync -avz --delete ./ $SSH_USER@ssh.getflywheel.com:$DEPLOY_PATH || {
            echo "Deployment failed"
            exit 1
          }

      - name: Verify Deployment
        run: |
          SSH_USER=${{ github.ref == 'refs/heads/main' && 'stompingground+stomping-ground' || 'stompingground+staging+stomping-ground' }}
          DEPLOY_PATH=${{ github.ref == 'refs/heads/main' && '/stompingground/stomping-ground' || '/stompingground/stomping-ground_staging' }}
          echo "Verifying deployment..."
          
          # Check if critical files exist
          ssh -v $SSH_USER@ssh.getflywheel.com "[ -f $DEPLOY_PATH/wp-config.php ]" || {
            echo "wp-config.php not found"
            exit 1
          }
          ssh -v $SSH_USER@ssh.getflywheel.com "[ -d $DEPLOY_PATH/wp-content/themes ]" || {
            echo "themes directory not found"
            exit 1
          }
          ssh -v $SSH_USER@ssh.getflywheel.com "[ -d $DEPLOY_PATH/wp-content/plugins ]" || {
            echo "plugins directory not found"
            exit 1
          } 